# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Publish package to the Maven Central Repository

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST: localhost
          POSGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and Publish package
      run: mvn -B clean deploy -Dit.postgresql.host=dockerbuild
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
